import frappe
from frappe import _
import os


@frappe.whitelist(allow_guest=True)
def get_theme_vars():
	"""
	Returns the CSS configuration variables from Entre Theme Settings as a dict.
	Called by theme.js on every desk page load and by the login renderer.
	Marked allow_guest=True so it can be called on the unauthenticated login page.
	"""
	try:
		settings = frappe.get_single("Entre Theme Settings")
		return {
			"primary_color": settings.primary_color or "#2B5CE6",
			"navbar_bg": settings.navbar_bg or "#1a1a2e",
			"sidebar_bg": settings.sidebar_bg or "#16213e",
			"font_family": settings.font_family or "Inter",
			"enable_animations": 1 if settings.enable_animations else 0,
			"custom_css": settings.custom_css or "",
		}
	except Exception:
		frappe.log_error(title="Entre Theme: get_theme_vars error", message=frappe.get_traceback())
		# Safe defaults — should always return something usable
		return {
			"primary_color": "#2B5CE6",
			"navbar_bg": "#1a1a2e",
			"sidebar_bg": "#16213e",
			"font_family": "Inter",
			"enable_animations": 1,
			"custom_css": "",
		}


@frappe.whitelist()
def apply_theme():
	"""
	Writes a runtime CSS file (theme_runtime.css) to the app's public/css folder,
	reflecting the current Entre Theme Settings values.

	The generated file is imported at the end of theme.css so it applies last
	and overrides any static defaults. After calling this, advise the user to
	run `bench build --app entre_theme` for the changes to take effect in prod.
	In developer mode changes are picked up immediately via the dev server.
	"""
	if not frappe.has_permission("Entre Theme Settings", "write"):
		frappe.throw(_("Not permitted"), frappe.PermissionError)

	settings = frappe.get_single("Entre Theme Settings")

	transition_value = (
		"all 0.2s cubic-bezier(0.4, 0, 0.2, 1)"
		if settings.enable_animations
		else "none"
	)

	css_content = (
		"/* Auto-generated by Entre Theme — do not edit manually */\n"
		":root {\n"
		f"\t--primary-color: {settings.primary_color or '#2B5CE6'};\n"
		f"\t--navbar-bg: {settings.navbar_bg or '#1a1a2e'};\n"
		f"\t--sidebar-bg: {settings.sidebar_bg or '#16213e'};\n"
		f"\t--font-family: '{settings.font_family or 'Inter'}', system-ui, -apple-system, sans-serif;\n"
		f"\t--transition: {transition_value};\n"
		"}\n"
	)

	try:
		# frappe.get_app_path returns the Python module dir, e.g.:
		#   /path/to/bench/apps/entre_theme/entre_theme
		# public/ lives one level up at:
		#   /path/to/bench/apps/entre_theme/public
		app_module_path = frappe.get_app_path("entre_theme")
		app_root_path = os.path.dirname(app_module_path)
		runtime_css_path = os.path.join(app_root_path, "public", "css", "theme_runtime.css")

		with open(runtime_css_path, "w", encoding="utf-8") as f:
			f.write(css_content)

		frappe.msgprint(
			_(
				"Theme settings written to <code>theme_runtime.css</code>.<br>"
				"In production, run <code>bench build --app entre_theme</code> "
				"to compile the updated assets."
			),
			title=_("Tema Aplicado"),
			indicator="green",
		)

	except OSError:
		frappe.log_error(
			title="Entre Theme: Failed to write theme_runtime.css",
			message=frappe.get_traceback(),
		)
		frappe.throw(
			_("Could not write the CSS file. Check the Error Log for details.")
		)
