app_name = "entre_theme"
app_title = "Entre Theme"
app_publisher = "Entretech"
app_description = "A non-destructive ERPNext theme app"
app_email = "hello@entretech.pt"
app_license = "mit"

# ─────────────────────────────────────────────
# Desk Assets (included in every logged-in page)
# ─────────────────────────────────────────────
app_include_css = [
	"/assets/entre_theme/css/theme.css",
	"/assets/entre_theme/css/components/navbar.css",
	"/assets/entre_theme/css/components/sidebar.css",
	"/assets/entre_theme/css/components/forms.css",
	# Generated by api.apply_theme(); defaults ship pre-populated
	"/assets/entre_theme/css/theme_runtime.css",
]
app_include_js = [
	"/assets/entre_theme/js/theme.js",
]

# ─────────────────────────────────────────────
# Web/Guest Assets (included on web pages like login)
# ─────────────────────────────────────────────
web_include_css = [
	"/assets/entre_theme/css/login.css",
]
web_include_js = [
	"/assets/entre_theme/js/login.js",
]

# ─────────────────────────────────────────────
# Custom Login Page Renderer
# ─────────────────────────────────────────────
page_renderer = ["entre_theme.overrides.login_renderer.LoginPageRenderer"]

# ─────────────────────────────────────────────
# Install / Uninstall Hooks
# ─────────────────────────────────────────────
after_install = "entre_theme.install.after_install"
before_uninstall = "entre_theme.install.before_uninstall"
