import os

import frappe


# ── Defaults written into theme_runtime.css on fresh install ──────────────────
_RUNTIME_CSS_DEFAULT = """\
/* Entre Theme — runtime variables.
   Generated by apply_theme or seeded by after_install.
   Re-run: bench build --app entre_theme  after any change. */
:root {
\t/* Tipografia & Global */
\t--font-family: 'Inter', system-ui, -apple-system, sans-serif;
\t--page-bg: #f3f4f6;
\t--border-radius: 8px;
\t--transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);

\t/* Cartões & Widgets */
\t--card-bg: #ffffff;
\t--card-border: #e5e7eb;
\t--card-shadow: 0px 4px 6px rgba(0,0,0,0.05);

\t/* Formulários & Inputs */
\t--input-bg: #f9fafb;
\t--input-border: #d1d5db;
\t--input-focus-ring: #2B5CE6;

\t/* Botões Principais */
\t--primary-color: #2B5CE6;
\t--primary-hover: #1e40af;
\t--primary-text: #ffffff;
\t--button-shadow: none;

\t/* Barra Lateral e Topo */
\t--navbar-bg: #1a1a2e;
\t--sidebar-bg: #16213e;
\t--sidebar-active-bg: #1f2937;
\t--sidebar-text: #9ca3af;
\t--sidebar-text-active: #ffffff;
}
"""


def _ensure_runtime_css():
	"""
	Write a default theme_runtime.css into public/css/ if the file does not
	already exist.  This prevents a 404 on the very first page load after
	`bench install-app entre_theme` but before the admin has ever clicked
	"Aplicar Tema".

	Uses os.path.realpath so symlinked bench apps (the common case) are
	resolved to their true on-disk location.
	"""
	app_module_path = frappe.get_app_path("entre_theme")
	# get_app_path → …/apps/entre_theme/entre_theme  (the Python package)
	# public/ is now a sibling inside that same folder:
	# → …/apps/entre_theme/entre_theme/public
	runtime_css = os.path.realpath(
		os.path.join(app_module_path, "public", "css", "theme_runtime.css")
	)

	if not os.path.exists(runtime_css):
		os.makedirs(os.path.dirname(runtime_css), exist_ok=True)
		with open(runtime_css, "w", encoding="utf-8") as f:
			f.write(_RUNTIME_CSS_DEFAULT)
		print(f"  Created: {runtime_css}")


def after_install():
	"""
	1. Seeds Entre Theme Settings with sensible defaults.
	2. Ensures theme_runtime.css exists so app_include_css never 404s on a
	   fresh install before the admin visits Entre Theme Settings.
	3. Prints build instructions.
	"""
	# ── 1. Seed settings ──────────────────────────────────────────────────────
	try:
		doc = frappe.get_single("Entre Theme Settings")
		if not doc.primary_color:
			doc.font_family = "Inter"
			doc.enable_animations = 1
			doc.page_bg = "#f3f4f6"
			doc.border_radius = "8px"
			doc.card_bg = "#ffffff"
			doc.card_border = "#e5e7eb"
			doc.card_shadow = "0px 4px 6px rgba(0,0,0,0.05)"
			doc.input_bg = "#f9fafb"
			doc.input_border = "#d1d5db"
			doc.input_focus_ring = "#2B5CE6"
			doc.primary_color = "#2B5CE6"
			doc.primary_color_hover = "#1e40af"
			doc.button_shadow = 0
			doc.primary_text_color = "#ffffff"
			doc.navbar_bg = "#1a1a2e"
			doc.sidebar_bg = "#16213e"
			doc.sidebar_active_bg = "#1f2937"
			doc.sidebar_text = "#9ca3af"
			doc.sidebar_text_active = "#ffffff"
			
			doc.save(ignore_permissions=True)
			frappe.db.commit()
	except Exception:
		# DocType may not yet be available during the very first migrate.
		pass

	# ── 2. Guarantee runtime CSS file exists ──────────────────────────────────
	try:
		_ensure_runtime_css()
	except Exception as e:
		# Non-fatal — the shipped placeholder in the repo covers most cases.
		print(f"  Warning: Could not create theme_runtime.css locally: {e}")

	# ── 3. Fix Bitnami permissions if applicable ──────────────────────────────
	try:
		import subprocess
		app_module_path = frappe.get_app_path("entre_theme")
		app_root = os.path.realpath(os.path.join(app_module_path, ".."))
		# Don't crash install if this fails (e.g., standard bench installs)
		subprocess.run(["sudo", "chown", "-R", "daemon:daemon", app_root], check=False)
	except Exception:
		pass

	# ── 4. Instructions ───────────────────────────────────────────────────────
	print("\n" + "=" * 60)
	print("  Entre Theme installed successfully!")
	print("  Run the following to compile assets:")
	print("    bench build --app entre_theme")
	print("=" * 60 + "\n")


def before_uninstall():
	"""
	Prints a clean uninstall message.
	Site data (Entre Theme Settings) is intentionally NOT deleted
	so that settings are preserved if the app is reinstalled.
	"""
	print("\n" + "=" * 60)
	print("  Uninstalling Entre Theme...")
	print("  Note: Settings data has been preserved in the database.")
	print("  To remove it manually: bench --site <site> execute")
	print("    frappe.delete_doc('Entre Theme Settings', 'Entre Theme Settings')")
	print("=" * 60 + "\n")
